[phases.setup]
nixPkgs = ["python39", "pip"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install -r requirements_railway.txt"
]

[phases.build]
cmds = [
    "mkdir -p weights/CodeFormer",
    "mkdir -p weights/facelib", 
    "mkdir -p weights/realesrgan",
    "mkdir -p weights/gfpgan"
]

[start]
cmd = "python simple_web_server.py"